### ISSUE TITLE
Failed to run migrate 

### ISSUE THREAD

**Issue by acapustean** [bradymholt/aspnet-core-react-template#48]
attached Windows logs, but on the Mac results as the same

**npm run migrate** 

```
> aspnet.core.react.template@1.0.0 migrate C:\test
> cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
child_process.js:660
    throw err;
    ^

Error: Command failed: dotnet ef migrations add 1580206668
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (C:\test\scripts\create-migration.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 43 6f 75 6c 64 20 6e 6f 74 20 65 78 65 63 75 74 65 20 62 65 63 61 75 73 65 20 74 68 65 20 73 70 65 63 69 66 69 65 64 20 63 6f 6d 6d 61 6e 64 20 6f 72 ... 305 more bytes>
  ],
  pid: 1208,
  stdout: <Buffer >,
  stderr: <Buffer 43 6f 75 6c 64 20 6e 6f 74 20 65 78 65 63 75 74 65 20 62 65 63 61 75 73 65 20 74 68 65 20 73 70 65 63 69 66 69 65 64 20 63 6f 6d 6d 61 6e 64 20 6f 72 ... 305 more bytes>
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aspnet.core.react.template@1.0.0 migrate: `cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aspnet.core.react.template@1.0.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

in Logs is mentioned that dotnet-ef is missed

 **dotnet tool install --global dotnet-ef**
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.1.1') was successfully installed.

**npm run migrate**

```
> aspnet.core.react.template@1.0.0 migrate C:\test
> cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update

child_process.js:660
    throw err;
    ^

Error: Command failed: dotnet ef migrations add 1580207402
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (C:\test\scripts\create-migration.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 42 75 69 6c 64 20 73 74 61 72 74 65 64 2e 2e 2e 0d 0a 42 75 69 6c 64 20 73 75 63 63 65 65 64 65 64 2e 0d 0a 53 79 73 74 65 6d 2e 49 6e 76 61 6c 69 64 ... 5945 more bytes>,
    <Buffer >
  ],
  pid: 13020,
  stdout: <Buffer 42 75 69 6c 64 20 73 74 61 72 74 65 64 2e 2e 2e 0d 0a 42 75 69 6c 64 20 73 75 63 63 65 65 64 65 64 2e 0d 0a 53 79 73 74 65 6d 2e 49 6e 76 61 6c 69 64 ... 5945 more bytes>,
  stderr: <Buffer >
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aspnet.core.react.template@1.0.0 migrate: `cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aspnet.core.react.template@1.0.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by acapustean** [comment]
clean master on macOS logs

**npm run migrate**

```
> aspnet.core.react.template@1.0.0 migrate /Users/admin/aspnet-core-react-template
> cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update

child_process.js:660
    throw err;
    ^

Error: Command failed: dotnet ef migrations add 1580218991
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (/Users/admin/aspnet-core-react-template/scripts/create-migration.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 59 6f 75 72 20 73 74 61 72 74 75 70 20 70 72 6f 6a 65 63 74 20 27 61 70 69 27 20 64 6f 65 73 6e 27 74 20 72 65 66 65 72 65 6e 63 65 20 4d 69 63 72 6f ... 179 more bytes>,
    <Buffer >
  ],
  pid: 11432,
  stdout: <Buffer 59 6f 75 72 20 73 74 61 72 74 75 70 20 70 72 6f 6a 65 63 74 20 27 61 70 69 27 20 64 6f 65 73 6e 27 74 20 72 65 66 65 72 65 6e 63 65 20 4d 69 63 72 6f ... 179 more bytes>,
  stderr: <Buffer >
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aspnet.core.react.template@1.0.0 migrate: `cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aspnet.core.react.template@1.0.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2020-01-28T13_43_17_040Z-debug.log
```
Log file 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'migrate' ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'premigrate', 'migrate', 'postmigrate' ]
5 info lifecycle aspnet.core.react.template@1.0.0~premigrate: aspnet.core.react.template@1.0.0
6 info lifecycle aspnet.core.react.template@1.0.0~migrate: aspnet.core.react.template@1.0.0
7 verbose lifecycle aspnet.core.react.template@1.0.0~migrate: unsafe-perm in lifecycle true
8 verbose lifecycle aspnet.core.react.template@1.0.0~migrate: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/admin/aspnet-core-react-template/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle aspnet.core.react.template@1.0.0~migrate: CWD: /Users/admin/aspnet-core-react-template
10 silly lifecycle aspnet.core.react.template@1.0.0~migrate: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update'
10 silly lifecycle ]
11 silly lifecycle aspnet.core.react.template@1.0.0~migrate: Returned: code: 1  signal: null
12 info lifecycle aspnet.core.react.template@1.0.0~migrate: Failed to exec migrate script
13 verbose stack Error: aspnet.core.react.template@1.0.0 migrate: `cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid aspnet.core.react.template@1.0.0
15 verbose cwd /Users/admin/aspnet-core-react-template
16 verbose Darwin 19.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "migrate"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error aspnet.core.react.template@1.0.0 migrate: `cd ./api/ && node ../scripts/create-migration.js && dotnet ef database update`
22 error Exit status 1
23 error Failed at the aspnet.core.react.template@1.0.0 migrate script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by acapustean** [comment]
maybe is need some additional manipulations, but with clean project on master branch or with new model the result is the same as in

**Comment by bradymholt** [comment]
@acapustean - I'd appreciate if you could troubleshoot it and submit a PR.  Thank you!

**Comment by bradymholt** [comment]
I just did the following and it worked:

- Cloned fresh
- npm run install
- npm run start
- npm run migrate

```
Build started...
Build succeeded.
Done.
```
